version: '3'
services:
  database:
    container_name: postgres_cnt
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/libs/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=users_db
    restart: always
volumes:
  pgdata: